language: java

before_install:
  - cp src/main/properties/log4j.properties src/test/resources/log4j.properties
  - mkdir -p "gerbil_data"
  - curl --retry 4 -L -o "gerbil_data/gerbil_data.zip" "http://139.18.2.164/mroeder/gerbil_data.zip"
  - unzip "gerbil_data/gerbil_data.zip"
  - touch src/main/properties/gerbil_keys.properties
install:
  - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package -Dmaven.javadoc.skip=true -B
